export const roleBasedRoutes = {
  admin: [
    "/dashboard",
    "/users",
    "/dishes",
    "/dishes/form",
    "/category",
    "/category/:id",
    "/resturant_category",
    "/resturant_category/:id",
    "/restaurants",
    "/restaurants/:id",
    "/restaurants/restaurantForm",
    "/orders",
    "/orders/:id",
    "/ordermanagement",
    "/restaurant-orders/:restaurantId",
    "/driver-transactions/:driverId",
    "/customerperformance",
    "/orderpaymentreport",
    "/storeperformancereport",
    "/storewisereport",
    "/order/:orderId", 
    "/assign/:orderId",
    "/delivery-collection" ,
    "/delivery-logs/:id", 
    "/transaction",
    "/DeliveryCollection",
    "/MostSoldItems",
    "/driver",
    "/review",
    "/banner",
    "/banner/form",
    "/coupons",
    "/settlements",
    "/coupons/form",
    // "restaurant/:id",
    "/coupons/form/:id",
    "/resturants_owner",
  ],
  restaurent: [
    "/restaurants_owner",
    "/SattelmentOwnner",
    "/restaurants_owner/:id",
    "/restaurants_owner/restaurantForm_owner",
    "/restaurants_owner/restaurantForm_owner/:id",
    "/restaurants_owner/restaurantForm_owner/:id/menu_form",
    "/restaurants_owner/restaurantForm_owner/:id/menu_form/:menuid",

    "/coupons_owner",
    "/coupons_owner/coupon_form",
    "/coupons_owner/coupon_form/:id",

    "/orders_owner",
  ],
  // driver: ["/orders_driver", "/driver_profile"],
};

export const baseRoute = {
  admin: "/users",
  restaurent: "/restaurants_owner",
  // driver: "/orders_driver",
};
