export const ENDPOINTS = {
  REGISTER: '/user/register',
  VERIFY_OTP: '/user/verify-otp',
  SIGNIN: '/user/signin',
  LOGIN_VERIFY: '/user/login-verify',
  UPDATE_USER: '/user/update-user',
  GET_USER_PROFILE: '/user/profile',
  SENT_FORGOT_PASSWORD_OTP: '/user/forgot-password',
  RESET_PASSWORD: '/user/forgot-reset-password',
  GET_ALL_DISHES: '/menus',
  GET_SPECIAL:'/menus/offers',
  GET_DISHES_BY_RESTAURANT: '/menus/restaurant',
  GET_DISHES_BY_CATEGORY: '/menus/categories',
  GET_DISHES_BY_TYPE: '/menus/dishtype',
  GET_ALL_RESTAURANTS: '/restaurant',
  GET_RESTAURANT_BY_ID: '/restaurant',
  GET_BANNER: '/banner',
  GET_FOOD_CATEGORIES: '/restcategory',
  GET_COUPONS: '/coupon',
  CREATE_ORDER: '/order',
  GET_ALL_ORDERS: '/order',
  GET_SINGLE_ORDER: '/order/get/one',
  ADD_TO_FAVOURITES:'/menus/favorites',
  GET_ALL_FAVORITES: '/restaurant/favorites',
  REVIEW:'/review',
  FILTER_BY_CATEGORY:'/restaurant//filter-by-category',
  ADD_FAVORITE_RESTAURANT:'/restaurant/favorites',
};
